FROM node:alpine AS builder

WORKDIR /build
COPY . .

RUN apk add python3 make g++ && \
  yarn install --frozen-lockfile && \
  npm run build && \
  rm -r node_modules

FROM nginx

COPY --from=builder /build/dist/* /usr/share/nginx/html/

COPY ./nginx.conf /etc/nginx/nginx.conf

