FROM node:alpine

WORKDIR /build
COPY . .
RUN ls

RUN yarn install --frozen-lockfile && \
  npm run build && \
  rm -r node_modules

FROM nginx

RUN mkdir -p /usr/share/nginx/html && \
  mv /build/dist/* /usr/share/nginx/html

COPY ./nginx.conf /etc/nginx/nginx.conf

