version: "3.8"
services:
  redis:
    container_name: riffy-redis
    image: redis
  database:
    container_name: riffy-database
    build: ./database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sogood
      - POSTGRES_DB=riffy
    volumes:
      - riffy-pg:/var/lib/postgres/data
      - ./database:/service
  ingress:
    container_name: riffy-ingress
    image: nginx:stable-alpine
    volumes:
      - ./docker-nginx.conf:/etc/nginx/nginx.conf
    ports: 
      - "3030:80"
  server:
    container_name: riffy-server
    build: ./server
    volumes: 
      - ./server:/service
      - /service/node_modules
    environment:
      - PORT=1234
  client:
    container_name: riffy-client
    build: ./client
    volumes:
      - ./client:/service
      - /service/node_modules
    ports:
      - "3031:3031"

volumes: 
  riffy-pg: