name: 'Build'
description: 'Builds and pushes a docker image'
inputs:
  context:
    required: true
  file:
    required: true
  tag:
    required: true
runs:
  using: "composite"
  steps:
    - uses: rlespinasse/github-slug-action@v3.x
    - run: 'echo "PROJECT_ENV=$(GITHUB_REF_SLUG=dev; . ./kubernetes/ci.sh;)" >> $GITHUB_ENV'
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.file }}
        platforms: linux/amd64
        push: true
        tags: '${{ inputs.tag }}:${{ env.PROJECT_ENV }}'