apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: riffy-server
  labels:
    app: riffy-server
spec:
  ports:
  - port: 1234
    name: riffy-server
  selector:
    app: riffy-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: riffy-server-deployment
  labels:
    app: riffy-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: riffy-server
  template:
    metadata:
      labels:
        app: riffy-server
    spec:
      containers:
      - name: riffy-server
        image: taavettik/riffy-server:latest
        env:
        - name: "PORT"
          value: "1234"
        - name: "DB_HOST"
          value: "95.217.8.74"
        # TODO: mount these as volumes
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: riffy-db-credentials
              key: password
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: riffy-db-credentials
              key: username