name: ci

on:
  push:
    branches: master

jobs:
  build-client:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Debug
        run: ls && ls ./client
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./client
          file: ./client/Dockerfile.build
          platforms: linux/386,linux/amd64
          push: true
          tags: ghcr.io/taavettik/riffy_client:latest