name: ci

on:
  push:
    branches: master

jobs:
  deploy-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Set up k8s
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBERNETES_CONFIG }}
      - uses: azure/k8s-create-secret@v1
        with:
          secret-type: 'generic'
          arguments:  --from-literal=password=${{ secrets.DB_PASSWORD }} --from-literal=username=riffy
          secret-name: riffy-db-credentials

  build-client:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./client
          file: ./client/Dockerfile.build
          platforms: linux/amd64
          push: true
          tags: taavettik/riffy-client:latest
  
  build-server:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./server
          file: ./server/Dockerfile.build
          platforms: linux/amd64
          push: true
          tags: taavettik/riffy-server:latest